### ISSUE TITLE
Is this only runable on Windows?

### ISSUE THREAD

**Issue by yangzhewen** [arenaxr/arena-unity#114]
Hey,  I am trying to render some 3D models from unity to the web (from a Linux machine), and it did not work and straight to the lobby via the link. This failure appears:

DllNotFoundException: AudioPluginAxelF assembly:<unknown assembly> type:<unknown type> member:(null) AxelF.Heartbeat.Update () (at Assets/Features/AxelF/Code/Heartbeat.cs:63)

Any idea of how to fix this? Thanks.

**Comment by mwfarb** [comment]
We support Windows, Linux, and Mac. Let's get to the bottom of it. Unfortunately I don't understand your difficulty yet. I'll start with some assumptions and ask some questions:
- I'm assuming you have an ARENA account setup and know what the ARENA XR system is: https://docs.arenaxr.org.
- You've already completed the steps at the Unity `Quick Start` link here: https://github.com/arenaxr/arena-unity/blob/main/README.md
- When you add the `ArenaClientScene` component and press Play you can manually export Unity objects as GLTF models which then upload to the web site https://arenaxr.org to view with these instructions: https://docs.arenaxr.org/content/unity/models
- Have you already done all of the above, or got stuck somewhere in those steps?
- Is the `link` you mean a web URL? A Unity Menu? A button on one of the Inspector panels from one of our components? What is it's name or address?
- What is the `lobby`? If you mean the Unity Lobby, it's not a feature we support and have never used. If fact this repo was built as an add on to interact with the ARENA XR 3d web collaboration framework: https://arenaxr.org/scenes. It doesn't need the Unity Lobby to share content, it would be redundant.
- `AudioPluginAxelF` isn't a package I'm aware our package uses, we don't support audio in Unity yet. 
- I hope this helps a little; it's unclear at what stage things went wrong.

**Comment by yangzhewen** [comment]
Hey, thanks for your reply. I have done steps 1,2,3 and built a scene with the BotD package (basically the forest example, I was trying to reproduce the example of [arena-renderfusion]). I thought the arena was able to render it from my pc to that web. But when I reached that URL, it was still the default empty plane like an online conference room. I might miss some of the instructions, so how to render the scene and the object to that web? 
![Uploading 截屏2024-11-22 14.44.04.png…]()

**Comment by mwfarb** [comment]
@EdwardLu2018 What do you think should the next steps here?

**Comment by EdwardLu2018** [comment]
@yangzhewen Can you show the unity console? Any errors? Which url are you going to on ARENA? Which url does it say on Unity?

**Comment by EdwardLu2018** [comment]
@yangzhewen If you want to quickly call or have faster replies, you can message me and @mwfarb on our public slack (If you want to quickly call, you can join our slack here (https://join.slack.com/t/arena-conix/shared_invite/zt-2varok4a8-MbJ6orKxmTvdv9eSTgWdSw)

**Comment by yangzhewen** [comment]
My scene seemed to be too complicated and big, and the web might not load it. I changed to a simpler scene and it worked. I'll join the slack and ask you guys if I have further questions. Thanks!
